---
- name: Install Docker and set up SonarQube container
  hosts: sonarqube
  become: true
  vars:
    sonarqube_volume_path: /var/lib/sonarqube
  tasks:
    - name: Check if Docker is installed
      stat:
        path: /usr/bin/docker
      register: docker_installed
      changed_when: false
    - name: Install Docker if not already installed
      apt:
        name: docker.io
        state: present
      when: not docker_installed.stat.exists
    - name: Start Docker service
      service:
        name: docker
        state: started
    - name: Set up SonarQube container
      docker_container:
        name: sonarqube
        image: sonarqube:lts
        state: started
        ports:
          - "9000:9000"
          - "9092:9092"
        volumes:
          - "{{ sonarqube_volume_path }}:/opt/sonarqube/data"
